Fix "_table_model.TableModel is not a constructor"
TypeError: _table_model.TableModel is not a constructor when switch from TimeSeries to Table format in the query